# Generated by Django 6.0.1 on 2026-01-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Nimi')),
                ('registry_code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Registrikood')),
                ('legal_form', models.CharField(blank=True, max_length=100, verbose_name='Õiguslik vorm')),
                ('status', models.CharField(blank=True, max_length=50, verbose_name='Staatus')),
                ('status_text', models.CharField(blank=True, max_length=100, verbose_name='Staatus tekstina')),
                ('registered_date', models.CharField(blank=True, max_length=20, verbose_name='Registreeritud')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Aadress')),
                ('county', models.CharField(blank=True, max_length=200, verbose_name='Piirkond')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Postiindeks')),
                ('vat_number', models.CharField(blank=True, max_length=20, verbose_name='KMKR number')),
                ('ceo', models.CharField(blank=True, max_length=200, verbose_name='Juht')),
                ('board_members', models.TextField(blank=True, verbose_name='Juhatuse liikmed')),
                ('employees', models.FloatField(blank=True, null=True, verbose_name='Töötajaid')),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Käive')),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Kasum')),
                ('report_year', models.CharField(blank=True, max_length=4, verbose_name='Aruande aasta')),
                ('registry_link', models.URLField(blank=True, max_length=500, verbose_name='Registri link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ettevõte',
                'verbose_name_plural': 'Ettevõtted',
                'ordering': ['name'],
            },
        ),
    ]
