# Generated by Django 6.0.1 on 2026-01-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='activity',
            field=models.CharField(blank=True, max_length=500, verbose_name='Tegevusala'),
        ),
        migrations.AddField(
            model_name='company',
            name='activity_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='EMTAK kood'),
        ),
        migrations.AddField(
            model_name='company',
            name='labor_taxes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Tööjõumaksud'),
        ),
        migrations.AddField(
            model_name='company',
            name='state_taxes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Riiklikud maksud'),
        ),
        migrations.AlterField(
            model_name='company',
            name='county',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Piirkond'),
        ),
        migrations.AlterField(
            model_name='company',
            name='employees',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Töötajaid'),
        ),
        migrations.AlterField(
            model_name='company',
            name='revenue',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=15, null=True, verbose_name='Käive'),
        ),
    ]
